name: Publish Docker
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: nodefortytwo/gha-terraform@${{ github.sha }}
        with:
          root_dir: "./terraform"
          action: "apply"
