name: Publish Docker
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nodefortytwo/gha-terraform@master
        with:
          root_dir: "./tests/workspace/terraform"
          action: "apply"
